export * from './agenda.service';
import { AgendaService } from './agenda.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './subscription-plan.service';
import { SubscriptionPlanService } from './subscription-plan.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AgendaService, AppService, AuthService, ClientsService, NotificationsService, PermissionsService, ProductsService, RolesService, StockService, SubscriptionService, SubscriptionPlanService, UsersService];
