/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardMetricsDto } from '../../models/dashboard-metrics-dto';

export interface DashboardControllerGetMetrics$Params {
}

export function dashboardControllerGetMetrics(http: HttpClient, rootUrl: string, params?: DashboardControllerGetMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardMetricsDto>> {
  const rb = new RequestBuilder(rootUrl, dashboardControllerGetMetrics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardMetricsDto>;
    })
  );
}

dashboardControllerGetMetrics.PATH = '/dashboard/metrics';
