/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomListResponseDto } from '../../models/room-list-response-dto';

export interface RoomControllerFindAll$Params {

/**
 * Search in name, description and location
 */
  search?: string;

/**
 * Filter by active status
 */
  isActive?: boolean;

/**
 * Page number
 */
  page?: number;

/**
 * Items per page
 */
  limit?: number;
}

export function roomControllerFindAll(http: HttpClient, rootUrl: string, params?: RoomControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomListResponseDto>> {
  const rb = new RequestBuilder(rootUrl, roomControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('isActive', params.isActive, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoomListResponseDto>;
    })
  );
}

roomControllerFindAll.PATH = '/rooms';
