/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceListResponseDto } from '../../models/service-list-response-dto';

export interface ServiceControllerFindAll$Params {

/**
 * Search in name and description
 */
  search?: string;

/**
 * Filter by category
 */
  category?: string;

/**
 * Filter by status
 */
  status?: 'ACTIVE' | 'INACTIVE';

/**
 * Page number
 */
  page?: number;

/**
 * Items per page
 */
  limit?: number;
}

export function serviceControllerFindAll(http: HttpClient, rootUrl: string, params?: ServiceControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceListResponseDto>> {
  const rb = new RequestBuilder(rootUrl, serviceControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('category', params.category, {});
    rb.query('status', params.status, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceListResponseDto>;
    })
  );
}

serviceControllerFindAll.PATH = '/service';
