/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadResponseDto } from '../../models/file-upload-response-dto';

export interface UploadControllerUploadFile$Params {
      body: {
'file'?: Blob;
'fileType'?: 'image' | 'document' | 'avatar' | 'thumbnail';
'entityType'?: 'user' | 'client' | 'product' | 'appointment' | 'general';
'entityId'?: number;
'description'?: string;
}
}

export function uploadControllerUploadFile(http: HttpClient, rootUrl: string, params: UploadControllerUploadFile$Params, context?: HttpContext): Observable<StrictHttpResponse<FileUploadResponseDto>> {
  const rb = new RequestBuilder(rootUrl, uploadControllerUploadFile.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileUploadResponseDto>;
    })
  );
}

uploadControllerUploadFile.PATH = '/upload';
