/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadResponseDto } from '../../models/file-upload-response-dto';

export interface UploadControllerGetMyFiles$Params {
}

export function uploadControllerGetMyFiles(http: HttpClient, rootUrl: string, params?: UploadControllerGetMyFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, uploadControllerGetMyFiles.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileUploadResponseDto>>;
    })
  );
}

uploadControllerGetMyFiles.PATH = '/api/upload/my-files';
