/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientResponseDto } from '../../models/client-response-dto';
import { CreateClientDto } from '../../models/create-client-dto';

export interface ClientControllerCreate$Params {
      body: CreateClientDto
}

export function clientControllerCreate(http: HttpClient, rootUrl: string, params: ClientControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, clientControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientResponseDto>;
    })
  );
}

clientControllerCreate.PATH = '/clients';
