/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientResponseDto } from '../../models/client-response-dto';
import { UpdateClientDto } from '../../models/update-client-dto';

export interface ClientControllerUpdate$Params {
  id: number;
      body: UpdateClientDto
}

export function clientControllerUpdate(http: HttpClient, rootUrl: string, params: ClientControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, clientControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientResponseDto>;
    })
  );
}

clientControllerUpdate.PATH = '/api/clients/{id}';
