/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientResponseDto } from '../../models/client-response-dto';

export interface ClientControllerFindOne$Params {
  id: number;

/**
 * Admin: ID del usuario dueño del cliente
 */
  userId?: number;
}

export function clientControllerFindOne(http: HttpClient, rootUrl: string, params: ClientControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, clientControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientResponseDto>;
    })
  );
}

clientControllerFindOne.PATH = '/clients/{id}';
