/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentProductLogResponseDto { 
    productId: number;
    name: string;
    quantity: number;
    priceAtTime: number;
    usedAt: string;
}

