/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentProfessionalResponseDto { 
    /**
     * ID del profesional (usuario)
     */
    id: number;
    /**
     * Nombre completo del profesional
     */
    fullName: string;
}

