/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SlotDetailDto } from './slot-detail-dto';


export interface AvailableSlotResponseDto { 
    /**
     * Fecha para la cual se listan los slots
     */
    date: string;
    /**
     * Lista de slots disponibles y no disponibles para el día
     */
    slots: Array<SlotDetailDto>;
    /**
     * Mensaje adicional (ej. si el día está bloqueado)
     */
    message?: string;
}

