/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateStockMovementDto { 
    productId: number;
    quantity: number;
    type: CreateStockMovementDto.TypeEnum;
    reason?: string;
}
export namespace CreateStockMovementDto {
    export type TypeEnum = 'in' | 'out' | 'adjustment' | 'usage';
    export const TypeEnum = {
        In: 'in' as TypeEnum,
        Out: 'out' as TypeEnum,
        Adjustment: 'adjustment' as TypeEnum,
        Usage: 'usage' as TypeEnum
    };
}


