/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';


export interface ProfileResponseDto { 
    id: number;
    email: string;
    name: string;
    lastName: string;
    isActive: boolean;
    roles: Array<RoleDto>;
    /**
     * Indica si el usuario puede gestionar la agenda.
     */
    canManageAgenda: boolean;
    /**
     * Indica si el usuario puede gestionar clientes.
     */
    canManageClients: boolean;
    /**
     * Indica si el usuario puede gestionar productos.
     */
    canManageProducts: boolean;
    /**
     * Indica si el usuario puede gestionar otros usuarios.
     */
    canManageUsers: boolean;
    /**
     * Fecha de creación.
     */
    createdAt: string;
    /**
     * Fecha de última actualización.
     */
    updatedAt: string;
}

