/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionResponseDto } from './permission-response-dto';


export interface RoleResponseDto { 
    /**
     * ID del rol
     */
    id: number;
    /**
     * Nombre del rol
     */
    name: string;
    /**
     * Descripción del rol
     */
    description: string;
    /**
     * Lista de permisos asociados a este rol
     */
    permissions: Array<PermissionResponseDto>;
}

