/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StockMovementResponseDto { 
    id: number;
    productId: number;
    productNameAtTime: string;
    quantity: number;
    type: StockMovementResponseDto.TypeEnum;
    reason?: string;
    createdAt: string;
}
export namespace StockMovementResponseDto {
    export type TypeEnum = 'in' | 'out' | 'adjustment' | 'usage';
    export const TypeEnum = {
        In: 'in' as TypeEnum,
        Out: 'out' as TypeEnum,
        Adjustment: 'adjustment' as TypeEnum,
        Usage: 'usage' as TypeEnum
    };
}


