/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAgendaConfigDto { 
    startTime: string;
    endTime: string;
    slotDuration: number;
    overbookingAllowed: boolean;
    allowBookingOnBlockedDays: boolean;
    workingDays: Array<string>;
}

