/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleResponseDto } from './role-response-dto';


export interface UserResponseDto { 
    id: number;
    email: string;
    fullName: string;
    isAdmin: boolean;
    active: boolean;
    createdAt: string;
    updatedAt: string;
    /**
     * Roles asignados al usuario
     */
    roles: Array<RoleResponseDto>;
}

