/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsultationTokenResponseDto } from '../../models/consultation-token-response-dto';

export interface ConsultationControllerGetTokensForConsultation$Params {
  id: number;
}

export function consultationControllerGetTokensForConsultation(http: HttpClient, rootUrl: string, params: ConsultationControllerGetTokensForConsultation$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConsultationTokenResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, consultationControllerGetTokensForConsultation.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConsultationTokenResponseDto>>;
    })
  );
}

consultationControllerGetTokensForConsultation.PATH = '/api/consultations/{id}/tokens';
