/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientCompleteHistoryDto } from '../../models/client-complete-history-dto';

export interface ClientPortalControllerGetHistory$Params {

/**
 * Página (default: 1)
 */
  page?: number;

/**
 * Elementos por página (default: 10)
 */
  limit?: number;
}

export function clientPortalControllerGetHistory(http: HttpClient, rootUrl: string, params?: ClientPortalControllerGetHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientCompleteHistoryDto>> {
  const rb = new RequestBuilder(rootUrl, clientPortalControllerGetHistory.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientCompleteHistoryDto>;
    })
  );
}

clientPortalControllerGetHistory.PATH = '/api/client/profile/history';
