/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientProfileResponseDto } from '../../models/client-profile-response-dto';

export interface ClientPortalControllerGetProfile$Params {
}

export function clientPortalControllerGetProfile(http: HttpClient, rootUrl: string, params?: ClientPortalControllerGetProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientProfileResponseDto>> {
  const rb = new RequestBuilder(rootUrl, clientPortalControllerGetProfile.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientProfileResponseDto>;
    })
  );
}

clientPortalControllerGetProfile.PATH = '/api/client/profile';
