/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientProfileResponseDto } from '../../models/client-profile-response-dto';
import { ClientProfileUpdateDto } from '../../models/client-profile-update-dto';

export interface ClientPortalControllerUpdateProfile$Params {
      body: ClientProfileUpdateDto
}

export function clientPortalControllerUpdateProfile(http: HttpClient, rootUrl: string, params: ClientPortalControllerUpdateProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientProfileResponseDto>> {
  const rb = new RequestBuilder(rootUrl, clientPortalControllerUpdateProfile.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientProfileResponseDto>;
    })
  );
}

clientPortalControllerUpdateProfile.PATH = '/api/client/profile';
