/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponseDto } from '../../models/product-response-dto';

export interface ProductControllerFindOne$Params {
  id: number;

/**
 * Admin: ID del usuario dueño del producto
 */
  userId?: number;
}

export function productControllerFindOne(http: HttpClient, rootUrl: string, params: ProductControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponseDto>> {
  const rb = new RequestBuilder(rootUrl, productControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponseDto>;
    })
  );
}

productControllerFindOne.PATH = '/products/{id}';
