/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponseDto } from '../../models/product-response-dto';

export interface ProductControllerFindAll$Params {

/**
 * Admin: ID del usuario cuyos productos se quieren ver
 */
  userId?: number;
}

export function productControllerFindAll(http: HttpClient, rootUrl: string, params?: ProductControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, productControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductResponseDto>>;
    })
  );
}

productControllerFindAll.PATH = '/api/products';
