/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubscriptionResponseDto } from '../../models/subscription-response-dto';

export interface SubscriptionControllerFindAll$Params {
}

export function subscriptionControllerFindAll(http: HttpClient, rootUrl: string, params?: SubscriptionControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubscriptionResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, subscriptionControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SubscriptionResponseDto>>;
    })
  );
}

subscriptionControllerFindAll.PATH = '/api/subscription';
