/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkAssignPermissionsDto } from '../../models/bulk-assign-permissions-dto';

export interface ModulesControllerBulkAssignPermissionsToRole$Params {
      body: BulkAssignPermissionsDto
}

export function modulesControllerBulkAssignPermissionsToRole(http: HttpClient, rootUrl: string, params: ModulesControllerBulkAssignPermissionsToRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, modulesControllerBulkAssignPermissionsToRole.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

modulesControllerBulkAssignPermissionsToRole.PATH = '/modules/permissions/assign-bulk';
