/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsultationTypeResponseDto } from '../../models/consultation-type-response-dto';

export interface ConsultationTypeControllerFindOne$Params {
  id: string;
}

export function consultationTypeControllerFindOne(http: HttpClient, rootUrl: string, params: ConsultationTypeControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ConsultationTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, consultationTypeControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConsultationTypeResponseDto>;
    })
  );
}

consultationTypeControllerFindOne.PATH = '/consultation-types/{id}';
