/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientLoginDto } from '../../models/client-login-dto';

export interface ClientAuthControllerLogin$Params {
      body: ClientLoginDto
}

export function clientAuthControllerLogin(http: HttpClient, rootUrl: string, params: ClientAuthControllerLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'access_token'?: string;
'client'?: {
'id'?: number;
'name'?: string;
'lastName'?: string;
'email'?: string;
'preferredName'?: string;
'membershipNumber'?: string;
'avatarUrl'?: string;
};
}>> {
  const rb = new RequestBuilder(rootUrl, clientAuthControllerLogin.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'access_token'?: string;
      'client'?: {
      'id'?: number;
      'name'?: string;
      'lastName'?: string;
      'email'?: string;
      'preferredName'?: string;
      'membershipNumber'?: string;
      'avatarUrl'?: string;
      };
      }>;
    })
  );
}

clientAuthControllerLogin.PATH = '/api/client/auth/login';
