/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConsultationTypeResponseDto } from '../../models/consultation-type-response-dto';
import { CreateConsultationTypeDto } from '../../models/create-consultation-type-dto';

export interface BusinessTypeControllerCreateConsultationType$Params {
      body: CreateConsultationTypeDto
}

export function businessTypeControllerCreateConsultationType(http: HttpClient, rootUrl: string, params: BusinessTypeControllerCreateConsultationType$Params, context?: HttpContext): Observable<StrictHttpResponse<ConsultationTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, businessTypeControllerCreateConsultationType.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConsultationTypeResponseDto>;
    })
  );
}

businessTypeControllerCreateConsultationType.PATH = '/api/business-types/consultation-types';
