/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BusinessTypeResponseDto } from '../../models/business-type-response-dto';
import { UpdateBusinessTypeDto } from '../../models/update-business-type-dto';

export interface BusinessTypeControllerUpdateBusinessType$Params {

/**
 * ID del tipo de negocio
 */
  id: number;
      body: UpdateBusinessTypeDto
}

export function businessTypeControllerUpdateBusinessType(http: HttpClient, rootUrl: string, params: BusinessTypeControllerUpdateBusinessType$Params, context?: HttpContext): Observable<StrictHttpResponse<BusinessTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, businessTypeControllerUpdateBusinessType.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BusinessTypeResponseDto>;
    })
  );
}

businessTypeControllerUpdateBusinessType.PATH = '/business-types/{id}';
