/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BusinessTypeResponseDto } from '../../models/business-type-response-dto';

export interface BusinessTypeControllerFindBusinessTypeByCode$Params {

/**
 * Código del tipo de negocio
 */
  code: string;
}

export function businessTypeControllerFindBusinessTypeByCode(http: HttpClient, rootUrl: string, params: BusinessTypeControllerFindBusinessTypeByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<BusinessTypeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, businessTypeControllerFindBusinessTypeByCode.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BusinessTypeResponseDto>;
    })
  );
}

businessTypeControllerFindBusinessTypeByCode.PATH = '/business-types/code/{code}';
