/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentProfessionalResponseDto {

  /**
   * Nombre completo del profesional
   */
  fullName: string;

  /**
   * ID del profesional (usuario)
   */
  id: number;
}
