/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentSummaryResponseDto {
  byDate: {
[key: string]: number;
};
  cancelled: number;
  checkedIn: number;
  completed: number;
  confirmed: number;
  inProgress: number;
  noShow: number;
  pending: number;
  total: number;
}
