/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentMetricsDto {
  cancelled: number;
  completed: number;
  confirmed: number;
  pending: number;
  thisMonth: number;
  thisWeek: number;
  today: number;
  total: number;
}
