/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentProductLogResponseDto {
  name: string;
  priceAtTime: number;
  productId: number;
  quantity: number;
  usedAt: string;
}
