/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignPermissionDto {

  /**
   * ID del permiso de módulo
   */
  permissionId: number;

  /**
   * ID del rol
   */
  roleId: number;
}
