/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookAppointmentDto {

  /**
   * ID del cliente para quien se reserva el turno (opcional)
   */
  clientId?: number;
  date: string;
  description?: string;

  /**
   * ID del profesional para quien se reserva el turno (opcional, si no es el usuario logueado)
   */
  professionalId?: number;
  time: string;
  title: string;
}
