/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkAssignPermissionsDto {

  /**
   * Array de IDs de permisos de módulo
   */
  permissionIds: Array<number>;

  /**
   * ID del rol
   */
  roleId: number;
}
