/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BusinessTypeMetricsDto {
  appointmentsCount: number;
  businessTypeId: number;
  businessTypeName: string;
  consultationsCount: number;
  revenue: number;
}
