/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BusinessTypeDto {

  /**
   * Código identificador del tipo de negocio
   */
  code: string;

  /**
   * Descripción del tipo de negocio
   */
  description: string;

  /**
   * ID único del tipo de negocio
   */
  id: number;

  /**
   * Nombre del tipo de negocio
   */
  name: string;
}
