/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientInvoiceHistoryDto } from '../models/client-invoice-history-dto';
import { ClientServiceHistoryDto } from '../models/client-service-history-dto';
export interface ClientCompleteHistoryDto {

  /**
   * Historial de facturas
   */
  invoices: Array<ClientInvoiceHistoryDto>;

  /**
   * Paginación
   */
  pagination: {
};

  /**
   * Historial de servicios
   */
  services: Array<ClientServiceHistoryDto>;

  /**
   * Estadísticas del cliente
   */
  stats: {
};
}
