/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AvatarDto } from '../models/avatar-dto';
export interface ClientResponseDto {
  address?: string;

  /**
   * Avatar object with file details
   */
  avatar?: AvatarDto;
  birthDate?: string;
  createdAt: string;

  /**
   * Date when client was deactivated
   */
  deactivatedAt?: string;

  /**
   * Reason for deactivation
   */
  deactivationReason?: string;

  /**
   * Número de documento de identidad
   */
  dniNumber?: string;

  /**
   * Tipo de documento de identidad
   */
  dniType?: 'DNI' | 'NIE' | 'PASAPORTE';
  email?: string;
  fullname: string;
  gender?: 'male' | 'female' | 'other';
  id: number;

  /**
   * Indicates if client is active (soft delete)
   */
  isActive: boolean;
  lastName: string;
  membershipNumber?: string;
  name: string;
  notes?: string;
  phone?: string;

  /**
   * Estado actual del cliente
   */
  status: 'ACTIVE' | 'INACTIVE' | 'CREATED' | 'UNUSED';
  updatedAt: string;
}
