/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAvailableRewardDto } from '../models/client-available-reward-dto';
import { ClientRewardHistoryDto } from '../models/client-reward-history-dto';
import { ClientRewardProgressDto } from '../models/client-reward-progress-dto';
export interface ClientRewardsSummaryDto {

  /**
   * Recompensas disponibles para canjear
   */
  availableRewards: Array<ClientAvailableRewardDto>;

  /**
   * Historial de actividad
   */
  history: Array<ClientRewardHistoryDto>;

  /**
   * Recompensas en progreso
   */
  inProgress: Array<ClientRewardProgressDto>;

  /**
   * Estadísticas generales
   */
  stats: {
};
}
