/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientMetricsDto {
  active: number;
  inactive: number;
  newThisMonth: number;
  newThisWeek: number;
  total: number;
}
