/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAppointmentResponseDto } from '../models/client-appointment-response-dto';
export interface ClientAppointmentsListDto {
  appointments: Array<ClientAppointmentResponseDto>;

  /**
   * Elementos por página
   */
  limit: number;

  /**
   * Página actual
   */
  page: number;

  /**
   * Total de citas
   */
  total: number;
}
