/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientRewardProgressDto {

  /**
   * Tipo de condición
   */
  conditionType: string;

  /**
   * Valor actual del cliente
   */
  currentValue: number;

  /**
   * Descripción del programa
   */
  description: string;

  /**
   * Está completado y listo para canjear
   */
  isCompleted: boolean;

  /**
   * ID del programa de recompensas
   */
  programId: number;

  /**
   * Nombre del programa
   */
  programName: string;

  /**
   * Porcentaje de progreso (0-100)
   */
  progressPercentage: number;

  /**
   * Tipo de recompensa
   */
  rewardType: string;

  /**
   * Valor de la recompensa
   */
  rewardValue: number;

  /**
   * Valor objetivo para completar
   */
  targetValue: number;

  /**
   * Fecha límite del programa
   */
  validUntil?: string;
}
