/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientAppointmentResponseDto {

  /**
   * Fecha y hora de la cita
   */
  appointmentDate: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Duración en minutos
   */
  durationMinutes?: number;

  /**
   * ID de la cita
   */
  id: number;

  /**
   * Notas de la cita
   */
  notes?: string;

  /**
   * Profesional asignado
   */
  professional?: {
};

  /**
   * Tipo de servicio
   */
  serviceType: string;

  /**
   * Estado de la cita
   */
  status: string;

  /**
   * Última actualización
   */
  updatedAt: string;
}
