/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientRewardHistoryDto {

  /**
   * Acción realizada
   */
  action: string;

  /**
   * Fecha de la acción
   */
  date: string;

  /**
   * Descripción del cambio
   */
  description: string;

  /**
   * ID del registro
   */
  id: number;

  /**
   * Nombre del programa
   */
  programName: string;

  /**
   * Valor asociado
   */
  value?: number;
}
