/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientResponseDto {
  address?: string;
  birthDate?: string;
  createdAt: string;
  email?: string;
  fullname: string;
  gender?: 'male' | 'female' | 'other';
  id: number;
  lastName: string;
  membershipNumber?: string;
  name: string;
  notes?: string;
  phone?: string;

  /**
   * Estado actual del cliente
   */
  status: 'ACTIVE' | 'INACTIVE' | 'CREATED' | 'UNUSED';
  updatedAt: string;
}
