/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateModulePermissionDto {

  /**
   * Acción del permiso
   */
  action: 'read' | 'write' | 'delete' | 'manage';

  /**
   * Descripción del permiso
   */
  description?: string;

  /**
   * Nombre para mostrar del permiso
   */
  displayName: string;

  /**
   * ID del módulo
   */
  moduleId: number;

  /**
   * Ámbito del permiso
   */
  scope: 'own' | 'group' | 'assigned';
}
