/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAppointmentDto {

  /**
   * Indica si el evento es de día completo
   */
  allDay?: boolean;

  /**
   * ID del cliente (paciente) asociado
   */
  clientId?: number;

  /**
   * Fecha y hora de fin del turno (ISO 8601)
   */
  endDateTime?: string;

  /**
   * Notas adicionales
   */
  notes?: string;

  /**
   * ID del profesional (usuario) asignado
   */
  professionalId?: number;

  /**
   * ID de la sala/recurso (opcional)
   */
  roomId?: number;

  /**
   * ID del servicio (opcional)
   */
  serviceId?: number;

  /**
   * Fecha y hora de inicio del turno (ISO 8601)
   */
  startDateTime: string;

  /**
   * Estado inicial del turno
   */
  status?: 'pending' | 'confirmed' | 'cancelled';

  /**
   * Título del turno
   */
  title: string;
}
