/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateClientDto {
  address?: string;
  birthDate?: string;
  email?: string;
  fullname: string;
  gender?: 'male' | 'female' | 'other';
  lastName: string;
  membershipNumber?: string;
  name: string;
  notes?: string;
  phone?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'CREATED' | 'UNUSED';
}
