/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInvoiceItemDto {

  /**
   * Descripción del item
   */
  description: string;

  /**
   * Descuento aplicado
   */
  discount?: number;
  discountType?: 'percentage' | 'fixed';

  /**
   * ID del servicio o producto
   */
  itemId: number;
  itemType: 'service' | 'product';

  /**
   * Notas del item
   */
  notes?: string;

  /**
   * Cantidad
   */
  quantity: number;

  /**
   * Precio unitario
   */
  unitPrice: number;
}
