/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSubscriptionPlanDto {
  description?: string;
  maxUsers: number;
  name: string;
  priceAnnual: number;
  priceMonthly: number;
  priceSemiannual: number;
}
