/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStockMovementDto {
  productId: number;
  quantity: number;
  reason?: string;
  type: 'in' | 'out' | 'adjustment' | 'usage';
}
