/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateServiceDto {
  basePrice: number;
  category?: string;
  description?: string;

  /**
   * Duration in minutes
   */
  duration?: number;
  name: string;
  notes?: string;
  status?: 'ACTIVE' | 'INACTIVE';
}
