/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DayOverrideDto {

  /**
   * Si está bloqueado completamente
   */
  blocked?: boolean;

  /**
   * Fecha específica para override (YYYY-MM-DD)
   */
  date: string;
  endTime?: string;
  note?: string;
  slotDuration?: number;
  startTime?: string;
}
