/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailLogResponseDto {
  bcc?: Array<string>;
  cc?: Array<string>;
  createdAt: string;
  deliveryStats?: {
};
  errorMessage?: string;
  failedAt?: string;
  id: string;
  relatedEntity?: {
};
  sentAt?: string;
  status: 'sent' | 'failed' | 'pending' | 'scheduled';
  subject: string;
  templateUsed?: string;
  to: Array<string>;
  userId?: string;
}
