/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmailAttachmentDto {
  content: string;
  contentType?: string;
  disposition?: 'attachment' | 'inline';
  filename: string;
}
