/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailLogResponseDto } from '../models/email-log-response-dto';
export interface EmailLogsPaginatedResponseDto {
  data: Array<EmailLogResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
