/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AvatarDto } from '../models/avatar-dto';
import { ProductDimensionsDto } from '../models/product-dimensions-dto';
import { ProductInventoryConfigDto } from '../models/product-inventory-config-dto';
import { ProductOwnerResponseDto } from '../models/product-owner-response-dto';
import { ProductPackagingDto } from '../models/product-packaging-dto';
export interface ExtendedProductResponseDto {
  availableStock: number;

  /**
   * Avatar object with file details
   */
  avatar?: AvatarDto;
  createdAt: string;
  currentPrice: number;
  daysUntilStockout?: number;
  description?: string;
  dimensions?: ProductDimensionsDto;
  id: number;
  inventoryConfig?: ProductInventoryConfigDto;
  name: string;
  owner: ProductOwnerResponseDto;
  packaging?: ProductPackagingDto;
  status: 'activo' | 'inactivo' | 'descatalogado' | 'agotado' | 'suspendido';
  stockLevel: 'high' | 'medium' | 'low' | 'out';
  stockValue?: number;
  suggestedReorderQuantity?: number;
  turnoverRate?: number;
  updatedAt: string;
}
