/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceItemResponseDto {
  description: string;
  discount: number;
  discountType: 'percentage' | 'fixed';
  id: number;
  itemId: number;
  itemType: 'service' | 'product';
  notes?: string;
  product?: {
};
  quantity: number;
  service?: {
};
  total: number;
  unitPrice: number;
}
