/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LowStockProductDto } from '../models/low-stock-product-dto';
export interface LowStockProductsDto {
  products: Array<LowStockProductDto>;
}
