/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponseDto {
  createdAt: string;
  id: number;
  message: string;
  read: boolean;
  title: string;
}
