/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AvatarDto } from '../models/avatar-dto';
import { ProductOwnerResponseDto } from '../models/product-owner-response-dto';
export interface ProductResponseDto {

  /**
   * Avatar object with file details
   */
  avatar?: AvatarDto;
  createdAt: string;
  currentPrice: number;
  description?: string;
  id: number;
  name: string;
  owner: ProductOwnerResponseDto;
  status: 'activo' | 'inactivo' | 'descatalogado' | 'agotado' | 'suspendido';
  updatedAt: string;
}
