/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductResponseDto } from '../models/product-response-dto';
export interface ProductSearchResponseDto {

  /**
   * Elementos por página
   */
  limit: number;

  /**
   * Página actual
   */
  page: number;

  /**
   * Lista de productos encontrados
   */
  products: Array<ProductResponseDto>;

  /**
   * Total de productos encontrados
   */
  total: number;

  /**
   * Total de páginas
   */
  totalPages: number;
}
