/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductOwnerResponseDto } from '../models/product-owner-response-dto';
export interface ProductResponseDto {
  createdAt: string;
  currentPrice: number;
  description?: string;
  id: number;
  imageUrl?: string;
  name: string;
  owner: ProductOwnerResponseDto;
  status: 'activo' | 'inactivo' | 'descatalogado' | 'agotado' | 'suspendido';
  thumbnailUrl?: string;
  updatedAt: string;
}
