/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleDto } from '../models/role-dto';
export interface ProfileResponseDto {

  /**
   * Indica si el usuario puede gestionar la agenda.
   */
  canManageAgenda: boolean;

  /**
   * Indica si el usuario puede gestionar clientes.
   */
  canManageClients: boolean;

  /**
   * Indica si el usuario puede gestionar productos.
   */
  canManageProducts: boolean;

  /**
   * Indica si el usuario puede gestionar otros usuarios.
   */
  canManageUsers: boolean;

  /**
   * Fecha de creación.
   */
  createdAt: string;
  email: string;
  id: number;
  isActive: boolean;
  lastName: string;
  name: string;
  roles: Array<RoleDto>;

  /**
   * Fecha de última actualización.
   */
  updatedAt: string;
}
