/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BusinessTypeDto } from '../models/business-type-dto';
export interface RewardProgramResponseDto {

  /**
   * Condiciones adicionales en formato JSON
   */
  additionalConditions: {
};

  /**
   * Información del tipo de negocio asociado
   */
  businessType: BusinessTypeDto;

  /**
   * Tipo de condición para ganar la recompensa
   */
  conditionType: 'VISIT_COUNT' | 'PURCHASE_AMOUNT' | 'SERVICE_COUNT' | 'CONSULTATION_COUNT';

  /**
   * Valor numérico de la condición (ej: 5 visitas, $100 de compra)
   */
  conditionValue: number;

  /**
   * Fecha de creación del programa
   */
  createdAt: string;

  /**
   * Descripción del programa
   */
  description: string;

  /**
   * ID único del programa de recompensas
   */
  id: number;

  /**
   * Máximo número de veces que un cliente puede usar esta recompensa
   */
  maxUsesPerCustomer: number;

  /**
   * Nombre del programa de recompensas
   */
  name: string;

  /**
   * Tipo de recompensa otorgada
   */
  rewardType: 'DISCOUNT_PERCENTAGE' | 'DISCOUNT_AMOUNT' | 'FREE_SERVICE' | 'POINTS';

  /**
   * Valor de la recompensa (ej: 20%, $50)
   */
  rewardValue: number;

  /**
   * Estado actual del programa
   */
  status: 'ACTIVE' | 'INACTIVE' | 'DRAFT';

  /**
   * Fecha de última actualización
   */
  updatedAt: string;

  /**
   * Fecha de inicio de validez del programa
   */
  validFrom: string;

  /**
   * Fecha de fin de validez del programa
   */
  validUntil: string;
}
