/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionResponseDto } from '../models/permission-response-dto';
export interface RoleResponseDto {

  /**
   * Descripción del rol
   */
  description: string;

  /**
   * ID del rol
   */
  id: number;

  /**
   * Nombre del rol
   */
  name: string;

  /**
   * Lista de permisos asociados a este rol
   */
  permissions: Array<PermissionResponseDto>;
}
