/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SlotDetailDto {

  /**
   * Indica si el slot está disponible
   */
  available: boolean;

  /**
   * Fecha y hora de fin del slot (ISO 8601)
   */
  end: string;

  /**
   * Fecha y hora de inicio del slot (ISO 8601)
   */
  start: string;

  /**
   * Hora del slot en formato HH:mm
   */
  time: string;
}
