/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockDistributionDto {
  empty: number;
  low: number;
  normal: number;
  over: number;
}
