/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubscriptionResponseDto {
  description: string;
  durationInMonths: number;
  id: number;
  name: string;
  price: number;
}
