/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubscriptionPlanFeatureResponseDto } from '../models/subscription-plan-feature-response-dto';
export interface SubscriptionPlanResponseDto {
  description?: string;
  features: Array<SubscriptionPlanFeatureResponseDto>;
  id: number;
  maxUsers: number;
  name: string;
  priceAnnual: number;
  priceMonthly: number;
  priceSemiannual: number;
}
