/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrendDto } from '../models/trend-dto';
export interface TrendsDto {
  lowStock: TrendDto;
  movements: TrendDto;
  products: TrendDto;
  value: TrendDto;
}
