/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductDimensionsDto {
  dimensionUnit: 'cm' | 'in' | 'm';
  height: number;
  length: number;
  volume?: number;
  volumeUnit: 'ml' | 'l' | 'cm3' | 'm3';
  weight: number;
  weightUnit: 'g' | 'kg' | 'lb' | 'oz';
  width: number;
}
