/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProductPackagingDto {
  barcode?: string;
  baseUnit: string;
  expirationMonths?: number;
  internalSku: string;
  minOrderQuantity: number;
  packageType: string;
  storageRequirements?: string;
  supplierSku?: string;
  unitsPerPackage: number;
}
