/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateRoleDto {

  /**
   * Description of the role
   */
  description?: string;

  /**
   * Unique name of the role
   */
  name?: string;

  /**
   * Array of permission IDs to assign to this role
   */
  permissionIds?: Array<number>;
}
