/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateModulePermissionDto {

  /**
   * Descripción del permiso
   */
  description?: string;

  /**
   * Nombre para mostrar del permiso
   */
  displayName?: string;
}
