/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateInvoiceItemDto } from '../models/create-invoice-item-dto';
export interface UpdateInvoiceDto {

  /**
   * ID del cliente
   */
  clientId?: number;

  /**
   * ID de la consulta relacionada
   */
  consultationId?: number;

  /**
   * Descuento general
   */
  discount?: number;
  discountType?: 'percentage' | 'fixed';

  /**
   * Fecha de vencimiento
   */
  dueDate?: string;

  /**
   * Items de la factura
   */
  items?: Array<CreateInvoiceItemDto>;

  /**
   * Notas de la factura
   */
  notes?: string;

  /**
   * Método de pago
   */
  paymentMethod?: 'cash' | 'card' | 'transfer' | 'check' | 'other';

  /**
   * Notas del pago
   */
  paymentNotes?: string;

  /**
   * Referencia del pago
   */
  paymentReference?: string;

  /**
   * Estado de la factura
   */
  status?: 'draft' | 'pending' | 'paid' | 'cancelled' | 'overdue';

  /**
   * Tasa de impuestos (%)
   */
  taxRate?: number;
}
