/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateConsultationDto {

  /**
   * Lista de alergias conocidas
   */
  allergies?: Array<string>;

  /**
   * ID de la cita relacionada
   */
  appointmentId?: number;

  /**
   * Presión arterial (ej: 120/80)
   */
  bloodPressure?: string;

  /**
   * ID del cliente/paciente
   */
  clientId?: number;

  /**
   * Diagnóstico realizado
   */
  diagnosis?: string;

  /**
   * Hora de fin de la consulta
   */
  endTime?: string;

  /**
   * Fecha de seguimiento
   */
  followUpDate?: string;

  /**
   * Requiere seguimiento
   */
  followUpRequired?: boolean;

  /**
   * Frecuencia cardíaca (bpm)
   */
  heartRate?: number;

  /**
   * Altura del cliente (m)
   */
  height?: number;

  /**
   * Medicamentos actuales
   */
  medications?: Array<string>;

  /**
   * Fecha para próxima cita
   */
  nextAppointment?: string;

  /**
   * Notas generales de la consulta
   */
  notes?: string;

  /**
   * Recomendaciones para el cliente
   */
  recommendations?: string;

  /**
   * Hora de inicio de la consulta
   */
  startTime?: string;

  /**
   * Estado de la consulta
   */
  status?: 'pending' | 'in_progress' | 'completed' | 'cancelled';

  /**
   * Síntomas reportados por el cliente
   */
  symptoms?: string;

  /**
   * Temperatura corporal (°C)
   */
  temperature?: number;

  /**
   * Tratamiento prescrito o realizado
   */
  treatment?: string;

  /**
   * Signos vitales adicionales (JSON)
   */
  vitals?: {
};

  /**
   * Peso del cliente (kg)
   */
  weight?: number;
}
