/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAgendaConfigDto {
  allowBookingOnBlockedDays: boolean;
  endTime: string;
  overbookingAllowed: boolean;
  slotDuration: number;
  startTime: string;
  workingDays: Array<string>;
}
