/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleResponseDto } from '../models/role-response-dto';
export interface UserResponseDto {
  active: boolean;
  avatarUrl?: string;
  createdAt: string;
  email: string;
  fullName: string;
  id: number;
  isAdmin: boolean;

  /**
   * Roles asignados al usuario
   */
  roles: Array<RoleResponseDto>;
  updatedAt: string;
}
