/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WebSocketStatsDto {
  connectedClients: number;
  rooms: {
};
  totalConnections: number;
}
