/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AgendaConfigResponseDto } from '../models/agenda-config-response-dto';
import { agendaControllerAddHoliday } from '../fn/agenda/agenda-controller-add-holiday';
import { AgendaControllerAddHoliday$Params } from '../fn/agenda/agenda-controller-add-holiday';
import { agendaControllerBook } from '../fn/agenda/agenda-controller-book';
import { AgendaControllerBook$Params } from '../fn/agenda/agenda-controller-book';
import { agendaControllerCreate } from '../fn/agenda/agenda-controller-create';
import { AgendaControllerCreate$Params } from '../fn/agenda/agenda-controller-create';
import { agendaControllerDeleteAppointment } from '../fn/agenda/agenda-controller-delete-appointment';
import { AgendaControllerDeleteAppointment$Params } from '../fn/agenda/agenda-controller-delete-appointment';
import { agendaControllerGetAppointments } from '../fn/agenda/agenda-controller-get-appointments';
import { AgendaControllerGetAppointments$Params } from '../fn/agenda/agenda-controller-get-appointments';
import { agendaControllerGetAvailable } from '../fn/agenda/agenda-controller-get-available';
import { AgendaControllerGetAvailable$Params } from '../fn/agenda/agenda-controller-get-available';
import { agendaControllerGetConfig } from '../fn/agenda/agenda-controller-get-config';
import { AgendaControllerGetConfig$Params } from '../fn/agenda/agenda-controller-get-config';
import { agendaControllerGetHolidays } from '../fn/agenda/agenda-controller-get-holidays';
import { AgendaControllerGetHolidays$Params } from '../fn/agenda/agenda-controller-get-holidays';
import { agendaControllerGetProductsUsed } from '../fn/agenda/agenda-controller-get-products-used';
import { AgendaControllerGetProductsUsed$Params } from '../fn/agenda/agenda-controller-get-products-used';
import { agendaControllerGetSummary } from '../fn/agenda/agenda-controller-get-summary';
import { AgendaControllerGetSummary$Params } from '../fn/agenda/agenda-controller-get-summary';
import { agendaControllerGetToday } from '../fn/agenda/agenda-controller-get-today';
import { AgendaControllerGetToday$Params } from '../fn/agenda/agenda-controller-get-today';
import { agendaControllerGetWeek } from '../fn/agenda/agenda-controller-get-week';
import { AgendaControllerGetWeek$Params } from '../fn/agenda/agenda-controller-get-week';
import { agendaControllerRegisterProductsUsed } from '../fn/agenda/agenda-controller-register-products-used';
import { AgendaControllerRegisterProductsUsed$Params } from '../fn/agenda/agenda-controller-register-products-used';
import { agendaControllerUpdate } from '../fn/agenda/agenda-controller-update';
import { AgendaControllerUpdate$Params } from '../fn/agenda/agenda-controller-update';
import { agendaControllerUpdateConfig } from '../fn/agenda/agenda-controller-update-config';
import { AgendaControllerUpdateConfig$Params } from '../fn/agenda/agenda-controller-update-config';
import { AppointmentProductLogResponseDto } from '../models/appointment-product-log-response-dto';
import { AppointmentResponseDto } from '../models/appointment-response-dto';
import { AppointmentSummaryResponseDto } from '../models/appointment-summary-response-dto';
import { AvailableSlotResponseDto } from '../models/available-slot-response-dto';
import { HolidayResponseDto } from '../models/holiday-response-dto';

@Injectable({ providedIn: 'root' })
export class AgendaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `agendaControllerGetAppointments()` */
  static readonly AgendaControllerGetAppointmentsPath = '/agenda';

  /**
   * Obtener turnos por diversos filtros (fecha, rango, estado, profesional).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetAppointments()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetAppointments$Response(params?: AgendaControllerGetAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentResponseDto>>> {
    return agendaControllerGetAppointments(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener turnos por diversos filtros (fecha, rango, estado, profesional).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetAppointments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetAppointments(params?: AgendaControllerGetAppointments$Params, context?: HttpContext): Observable<Array<AppointmentResponseDto>> {
    return this.agendaControllerGetAppointments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppointmentResponseDto>>): Array<AppointmentResponseDto> => r.body)
    );
  }

  /** Path part for operation `agendaControllerCreate()` */
  static readonly AgendaControllerCreatePath = '/agenda';

  /**
   * Crear un turno manual.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerCreate$Response(params: AgendaControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentResponseDto>> {
    return agendaControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un turno manual.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerCreate(params: AgendaControllerCreate$Params, context?: HttpContext): Observable<AppointmentResponseDto> {
    return this.agendaControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AppointmentResponseDto>): AppointmentResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerDeleteAppointment()` */
  static readonly AgendaControllerDeleteAppointmentPath = '/agenda/{id}';

  /**
   * Eliminar un turno (o marcarlo como cancelado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerDeleteAppointment()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerDeleteAppointment$Response(params: AgendaControllerDeleteAppointment$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentResponseDto>> {
    return agendaControllerDeleteAppointment(this.http, this.rootUrl, params, context);
  }

  /**
   * Eliminar un turno (o marcarlo como cancelado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerDeleteAppointment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerDeleteAppointment(params: AgendaControllerDeleteAppointment$Params, context?: HttpContext): Observable<AppointmentResponseDto> {
    return this.agendaControllerDeleteAppointment$Response(params, context).pipe(
      map((r: StrictHttpResponse<AppointmentResponseDto>): AppointmentResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerUpdate()` */
  static readonly AgendaControllerUpdatePath = '/agenda/{id}';

  /**
   * Actualizar un turno existente.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerUpdate$Response(params: AgendaControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentResponseDto>> {
    return agendaControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un turno existente.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerUpdate(params: AgendaControllerUpdate$Params, context?: HttpContext): Observable<AppointmentResponseDto> {
    return this.agendaControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AppointmentResponseDto>): AppointmentResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerBook()` */
  static readonly AgendaControllerBookPath = '/agenda/book';

  /**
   * Reservar un turno en un slot disponible (cliente o profesional).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerBook$Response(params: AgendaControllerBook$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentResponseDto>> {
    return agendaControllerBook(this.http, this.rootUrl, params, context);
  }

  /**
   * Reservar un turno en un slot disponible (cliente o profesional).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerBook(params: AgendaControllerBook$Params, context?: HttpContext): Observable<AppointmentResponseDto> {
    return this.agendaControllerBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<AppointmentResponseDto>): AppointmentResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetAvailable()` */
  static readonly AgendaControllerGetAvailablePath = '/agenda/available';

  /**
   * Ver slots disponibles para un día y profesional.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetAvailable()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetAvailable$Response(params: AgendaControllerGetAvailable$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailableSlotResponseDto>> {
    return agendaControllerGetAvailable(this.http, this.rootUrl, params, context);
  }

  /**
   * Ver slots disponibles para un día y profesional.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetAvailable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetAvailable(params: AgendaControllerGetAvailable$Params, context?: HttpContext): Observable<AvailableSlotResponseDto> {
    return this.agendaControllerGetAvailable$Response(params, context).pipe(
      map((r: StrictHttpResponse<AvailableSlotResponseDto>): AvailableSlotResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetConfig()` */
  static readonly AgendaControllerGetConfigPath = '/agenda/config';

  /**
   * Obtener configuración de agenda del profesional actual (o especificado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetConfig()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetConfig$Response(params?: AgendaControllerGetConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<AgendaConfigResponseDto>> {
    return agendaControllerGetConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener configuración de agenda del profesional actual (o especificado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetConfig$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetConfig(params?: AgendaControllerGetConfig$Params, context?: HttpContext): Observable<AgendaConfigResponseDto> {
    return this.agendaControllerGetConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<AgendaConfigResponseDto>): AgendaConfigResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerUpdateConfig()` */
  static readonly AgendaControllerUpdateConfigPath = '/agenda/config';

  /**
   * Actualizar configuración de agenda del profesional actual (o especificado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerUpdateConfig()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerUpdateConfig$Response(params: AgendaControllerUpdateConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<AgendaConfigResponseDto>> {
    return agendaControllerUpdateConfig(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar configuración de agenda del profesional actual (o especificado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerUpdateConfig$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerUpdateConfig(params: AgendaControllerUpdateConfig$Params, context?: HttpContext): Observable<AgendaConfigResponseDto> {
    return this.agendaControllerUpdateConfig$Response(params, context).pipe(
      map((r: StrictHttpResponse<AgendaConfigResponseDto>): AgendaConfigResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerAddHoliday()` */
  static readonly AgendaControllerAddHolidayPath = '/agenda/holiday';

  /**
   * Agregar feriado para un profesional.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerAddHoliday()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerAddHoliday$Response(params: AgendaControllerAddHoliday$Params, context?: HttpContext): Observable<StrictHttpResponse<HolidayResponseDto>> {
    return agendaControllerAddHoliday(this.http, this.rootUrl, params, context);
  }

  /**
   * Agregar feriado para un profesional.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerAddHoliday$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerAddHoliday(params: AgendaControllerAddHoliday$Params, context?: HttpContext): Observable<HolidayResponseDto> {
    return this.agendaControllerAddHoliday$Response(params, context).pipe(
      map((r: StrictHttpResponse<HolidayResponseDto>): HolidayResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetHolidays()` */
  static readonly AgendaControllerGetHolidaysPath = '/agenda/holidays';

  /**
   * Listar feriados de un profesional.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetHolidays()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetHolidays$Response(params?: AgendaControllerGetHolidays$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HolidayResponseDto>>> {
    return agendaControllerGetHolidays(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar feriados de un profesional.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetHolidays$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetHolidays(params?: AgendaControllerGetHolidays$Params, context?: HttpContext): Observable<Array<HolidayResponseDto>> {
    return this.agendaControllerGetHolidays$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HolidayResponseDto>>): Array<HolidayResponseDto> => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetSummary()` */
  static readonly AgendaControllerGetSummaryPath = '/agenda/summary';

  /**
   * Resumen de citas por estado y día para un profesional.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetSummary$Response(params: AgendaControllerGetSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentSummaryResponseDto>> {
    return agendaControllerGetSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * Resumen de citas por estado y día para un profesional.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetSummary(params: AgendaControllerGetSummary$Params, context?: HttpContext): Observable<AppointmentSummaryResponseDto> {
    return this.agendaControllerGetSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<AppointmentSummaryResponseDto>): AppointmentSummaryResponseDto => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetToday()` */
  static readonly AgendaControllerGetTodayPath = '/agenda/today';

  /**
   * Turnos del día actual del profesional logueado (o especificado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetToday()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetToday$Response(params?: AgendaControllerGetToday$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentResponseDto>>> {
    return agendaControllerGetToday(this.http, this.rootUrl, params, context);
  }

  /**
   * Turnos del día actual del profesional logueado (o especificado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetToday$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetToday(params?: AgendaControllerGetToday$Params, context?: HttpContext): Observable<Array<AppointmentResponseDto>> {
    return this.agendaControllerGetToday$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppointmentResponseDto>>): Array<AppointmentResponseDto> => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetWeek()` */
  static readonly AgendaControllerGetWeekPath = '/agenda/week';

  /**
   * Turnos de la semana actual del profesional logueado (o especificado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetWeek()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetWeek$Response(params?: AgendaControllerGetWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentResponseDto>>> {
    return agendaControllerGetWeek(this.http, this.rootUrl, params, context);
  }

  /**
   * Turnos de la semana actual del profesional logueado (o especificado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetWeek$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetWeek(params?: AgendaControllerGetWeek$Params, context?: HttpContext): Observable<Array<AppointmentResponseDto>> {
    return this.agendaControllerGetWeek$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppointmentResponseDto>>): Array<AppointmentResponseDto> => r.body)
    );
  }

  /** Path part for operation `agendaControllerRegisterProductsUsed()` */
  static readonly AgendaControllerRegisterProductsUsedPath = '/agenda/{id}/products-used';

  /**
   * Registrar productos utilizados en la cita.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerRegisterProductsUsed()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerRegisterProductsUsed$Response(params: AgendaControllerRegisterProductsUsed$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return agendaControllerRegisterProductsUsed(this.http, this.rootUrl, params, context);
  }

  /**
   * Registrar productos utilizados en la cita.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerRegisterProductsUsed$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agendaControllerRegisterProductsUsed(params: AgendaControllerRegisterProductsUsed$Params, context?: HttpContext): Observable<void> {
    return this.agendaControllerRegisterProductsUsed$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `agendaControllerGetProductsUsed()` */
  static readonly AgendaControllerGetProductsUsedPath = '/agenda/{id}/products';

  /**
   * Obtener productos utilizados en una cita.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agendaControllerGetProductsUsed()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetProductsUsed$Response(params: AgendaControllerGetProductsUsed$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentProductLogResponseDto>>> {
    return agendaControllerGetProductsUsed(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener productos utilizados en una cita.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agendaControllerGetProductsUsed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agendaControllerGetProductsUsed(params: AgendaControllerGetProductsUsed$Params, context?: HttpContext): Observable<Array<AppointmentProductLogResponseDto>> {
    return this.agendaControllerGetProductsUsed$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppointmentProductLogResponseDto>>): Array<AppointmentProductLogResponseDto> => r.body)
    );
  }

}
