/* tslint:disable */
 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authControllerGetProfile } from '../fn/auth/auth-controller-get-profile';
import { AuthControllerGetProfile$Params } from '../fn/auth/auth-controller-get-profile';
import { authControllerLogin } from '../fn/auth/auth-controller-login';
import { AuthControllerLogin$Params } from '../fn/auth/auth-controller-login';
import { authControllerRegister } from '../fn/auth/auth-controller-register';
import { AuthControllerRegister$Params } from '../fn/auth/auth-controller-register';
import { ProfileResponseDto } from '../models/profile-response-dto';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authControllerRegister()` */
  static readonly AuthControllerRegisterPath = '/auth/register';

  /**
   * Registro de usuario principal con suscripción.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRegister()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegister$Response(params: AuthControllerRegister$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerRegister(this.http, this.rootUrl, params, context);
  }

  /**
   * Registro de usuario principal con suscripción.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRegister$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegister(params: AuthControllerRegister$Params, context?: HttpContext): Observable<void> {
    return this.authControllerRegister$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerLogin()` */
  static readonly AuthControllerLoginPath = '/auth/login';

  /**
   * Login de usuario, devuelve JWT.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLogin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin$Response(params: AuthControllerLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authControllerLogin(this.http, this.rootUrl, params, context);
  }

  /**
   * Login de usuario, devuelve JWT.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLogin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin(params: AuthControllerLogin$Params, context?: HttpContext): Observable<void> {
    return this.authControllerLogin$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authControllerGetProfile()` */
  static readonly AuthControllerGetProfilePath = '/auth/profile';

  /**
   * Obtener datos del usuario autenticado.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerGetProfile()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetProfile$Response(params?: AuthControllerGetProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfileResponseDto>> {
    return authControllerGetProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener datos del usuario autenticado.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerGetProfile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerGetProfile(params?: AuthControllerGetProfile$Params, context?: HttpContext): Observable<ProfileResponseDto> {
    return this.authControllerGetProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProfileResponseDto>): ProfileResponseDto => r.body)
    );
  }

}
