/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { clientControllerCreate } from '../fn/clients/client-controller-create';
import { ClientControllerCreate$Params } from '../fn/clients/client-controller-create';
import { clientControllerDeactivate } from '../fn/clients/client-controller-deactivate';
import { ClientControllerDeactivate$Params } from '../fn/clients/client-controller-deactivate';
import { clientControllerFindActiveClients } from '../fn/clients/client-controller-find-active-clients';
import { ClientControllerFindActiveClients$Params } from '../fn/clients/client-controller-find-active-clients';
import { clientControllerFindAll } from '../fn/clients/client-controller-find-all';
import { ClientControllerFindAll$Params } from '../fn/clients/client-controller-find-all';
import { clientControllerFindGroupClients } from '../fn/clients/client-controller-find-group-clients';
import { ClientControllerFindGroupClients$Params } from '../fn/clients/client-controller-find-group-clients';
import { clientControllerFindOne } from '../fn/clients/client-controller-find-one';
import { ClientControllerFindOne$Params } from '../fn/clients/client-controller-find-one';
import { clientControllerReactivate } from '../fn/clients/client-controller-reactivate';
import { ClientControllerReactivate$Params } from '../fn/clients/client-controller-reactivate';
import { clientControllerRemove } from '../fn/clients/client-controller-remove';
import { ClientControllerRemove$Params } from '../fn/clients/client-controller-remove';
import { clientControllerUpdate } from '../fn/clients/client-controller-update';
import { ClientControllerUpdate$Params } from '../fn/clients/client-controller-update';
import { ClientResponseDto } from '../models/client-response-dto';

@Injectable({ providedIn: 'root' })
export class ClientsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `clientControllerFindAll()` */
  static readonly ClientControllerFindAllPath = '/clients';

  /**
   * Listar clientes (admin puede ver los de un sub-usuario).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindAll$Response(params?: ClientControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientResponseDto>>> {
    return clientControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar clientes (admin puede ver los de un sub-usuario).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindAll(params?: ClientControllerFindAll$Params, context?: HttpContext): Observable<Array<ClientResponseDto>> {
    return this.clientControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ClientResponseDto>>): Array<ClientResponseDto> => r.body)
    );
  }

  /** Path part for operation `clientControllerCreate()` */
  static readonly ClientControllerCreatePath = '/clients';

  /**
   * Crear un nuevo cliente.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerCreate$Response(params: ClientControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
    return clientControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Crear un nuevo cliente.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerCreate(params: ClientControllerCreate$Params, context?: HttpContext): Observable<ClientResponseDto> {
    return this.clientControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientResponseDto>): ClientResponseDto => r.body)
    );
  }

  /** Path part for operation `clientControllerFindGroupClients()` */
  static readonly ClientControllerFindGroupClientsPath = '/clients/group';

  /**
   * Listar todos los clientes del grupo (admin y sub-usuarios).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerFindGroupClients()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindGroupClients$Response(params?: ClientControllerFindGroupClients$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientResponseDto>>> {
    return clientControllerFindGroupClients(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar todos los clientes del grupo (admin y sub-usuarios).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerFindGroupClients$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindGroupClients(params?: ClientControllerFindGroupClients$Params, context?: HttpContext): Observable<Array<ClientResponseDto>> {
    return this.clientControllerFindGroupClients$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ClientResponseDto>>): Array<ClientResponseDto> => r.body)
    );
  }

  /** Path part for operation `clientControllerFindActiveClients()` */
  static readonly ClientControllerFindActiveClientsPath = '/clients/active-only';

  /**
   * Obtener solo clientes activos (para uso en citas y servicios).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerFindActiveClients()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindActiveClients$Response(params?: ClientControllerFindActiveClients$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientResponseDto>>> {
    return clientControllerFindActiveClients(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener solo clientes activos (para uso en citas y servicios).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerFindActiveClients$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindActiveClients(params?: ClientControllerFindActiveClients$Params, context?: HttpContext): Observable<Array<ClientResponseDto>> {
    return this.clientControllerFindActiveClients$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ClientResponseDto>>): Array<ClientResponseDto> => r.body)
    );
  }

  /** Path part for operation `clientControllerFindOne()` */
  static readonly ClientControllerFindOnePath = '/clients/{id}';

  /**
   * Obtener detalles de un cliente (admin puede ver los de un sub-usuario).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindOne$Response(params: ClientControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
    return clientControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Obtener detalles de un cliente (admin puede ver los de un sub-usuario).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerFindOne(params: ClientControllerFindOne$Params, context?: HttpContext): Observable<ClientResponseDto> {
    return this.clientControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientResponseDto>): ClientResponseDto => r.body)
    );
  }

  /** Path part for operation `clientControllerRemove()` */
  static readonly ClientControllerRemovePath = '/clients/{id}';

  /**
   * Eliminar un cliente permanentemente (no recomendado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerRemove$Response(params: ClientControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return clientControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Eliminar un cliente permanentemente (no recomendado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerRemove(params: ClientControllerRemove$Params, context?: HttpContext): Observable<void> {
    return this.clientControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `clientControllerUpdate()` */
  static readonly ClientControllerUpdatePath = '/clients/{id}';

  /**
   * Actualizar un cliente.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerUpdate$Response(params: ClientControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
    return clientControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Actualizar un cliente.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerUpdate(params: ClientControllerUpdate$Params, context?: HttpContext): Observable<ClientResponseDto> {
    return this.clientControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientResponseDto>): ClientResponseDto => r.body)
    );
  }

  /** Path part for operation `clientControllerDeactivate()` */
  static readonly ClientControllerDeactivatePath = '/clients/{id}/deactivate';

  /**
   * Desactivar un cliente (soft delete).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerDeactivate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerDeactivate$Response(params: ClientControllerDeactivate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
    return clientControllerDeactivate(this.http, this.rootUrl, params, context);
  }

  /**
   * Desactivar un cliente (soft delete).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerDeactivate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  clientControllerDeactivate(params: ClientControllerDeactivate$Params, context?: HttpContext): Observable<ClientResponseDto> {
    return this.clientControllerDeactivate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientResponseDto>): ClientResponseDto => r.body)
    );
  }

  /** Path part for operation `clientControllerReactivate()` */
  static readonly ClientControllerReactivatePath = '/clients/{id}/reactivate';

  /**
   * Reactivar un cliente desactivado.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clientControllerReactivate()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerReactivate$Response(params: ClientControllerReactivate$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponseDto>> {
    return clientControllerReactivate(this.http, this.rootUrl, params, context);
  }

  /**
   * Reactivar un cliente desactivado.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clientControllerReactivate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clientControllerReactivate(params: ClientControllerReactivate$Params, context?: HttpContext): Observable<ClientResponseDto> {
    return this.clientControllerReactivate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientResponseDto>): ClientResponseDto => r.body)
    );
  }

}
