/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PermissionResponseDto } from '../models/permission-response-dto';
import { permissionsControllerFindAll } from '../fn/permissions/permissions-controller-find-all';
import { PermissionsControllerFindAll$Params } from '../fn/permissions/permissions-controller-find-all';

@Injectable({ providedIn: 'root' })
export class PermissionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `permissionsControllerFindAll()` */
  static readonly PermissionsControllerFindAllPath = '/api/permissions';

  /**
   * Retrieve all permissions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `permissionsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  permissionsControllerFindAll$Response(params?: PermissionsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PermissionResponseDto>>> {
    return permissionsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieve all permissions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `permissionsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  permissionsControllerFindAll(params?: PermissionsControllerFindAll$Params, context?: HttpContext): Observable<Array<PermissionResponseDto>> {
    return this.permissionsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PermissionResponseDto>>): Array<PermissionResponseDto> => r.body)
    );
  }

}
