/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { testUploadControllerTestDebugUpload } from '../fn/test-upload/test-upload-controller-test-debug-upload';
import { TestUploadControllerTestDebugUpload$Params } from '../fn/test-upload/test-upload-controller-test-debug-upload';

@Injectable({ providedIn: 'root' })
export class TestUploadService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `testUploadControllerTestDebugUpload()` */
  static readonly TestUploadControllerTestDebugUploadPath = '/test-upload/debug';

  /**
   * Debug endpoint para probar entityId.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testUploadControllerTestDebugUpload()` instead.
   *
   * This method doesn't expect any request body.
   */
  testUploadControllerTestDebugUpload$Response(params?: TestUploadControllerTestDebugUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return testUploadControllerTestDebugUpload(this.http, this.rootUrl, params, context);
  }

  /**
   * Debug endpoint para probar entityId.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testUploadControllerTestDebugUpload$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testUploadControllerTestDebugUpload(params?: TestUploadControllerTestDebugUpload$Params, context?: HttpContext): Observable<void> {
    return this.testUploadControllerTestDebugUpload$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
