/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductResponseDto { 
    id: number;
    name: string;
    description?: string;
    status: ProductResponseDto.StatusEnum;
    currentPrice: number;
    createdAt: string;
    updatedAt: string;
}
export namespace ProductResponseDto {
    export type StatusEnum = 'activo' | 'inactivo' | 'descatalogado' | 'agotado' | 'suspendido';
    export const StatusEnum = {
        Activo: 'activo' as StatusEnum,
        Inactivo: 'inactivo' as StatusEnum,
        Descatalogado: 'descatalogado' as StatusEnum,
        Agotado: 'agotado' as StatusEnum,
        Suspendido: 'suspendido' as StatusEnum
    };
}


