export * from './agenda.service';
import { AgendaService } from './agenda.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AgendaService, AppService, AuthService, ClientsService, NotificationsService, ProductsService, StockService, SubscriptionService, UserService];
