/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInvoiceDto } from '../../models/create-invoice-dto';
import { InvoiceResponseDto } from '../../models/invoice-response-dto';

export interface InvoiceControllerCreate$Params {
      body: CreateInvoiceDto
}

export function invoiceControllerCreate(http: HttpClient, rootUrl: string, params: InvoiceControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, invoiceControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceResponseDto>;
    })
  );
}

invoiceControllerCreate.PATH = '/invoices';
