/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoiceResponseDto } from '../../models/invoice-response-dto';

export interface InvoiceControllerCancel$Params {
  id: number;
}

export function invoiceControllerCancel(http: HttpClient, rootUrl: string, params: InvoiceControllerCancel$Params, context?: HttpContext): Observable<StrictHttpResponse<InvoiceResponseDto>> {
  const rb = new RequestBuilder(rootUrl, invoiceControllerCancel.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvoiceResponseDto>;
    })
  );
}

invoiceControllerCancel.PATH = '/api/invoices/{id}/cancel';
