/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentResponseDto } from '../../models/appointment-response-dto';

export interface AgendaControllerGetWeek$Params {

/**
 * ID del profesional (admin)
 */
  professionalId?: number;
}

export function agendaControllerGetWeek(http: HttpClient, rootUrl: string, params?: AgendaControllerGetWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, agendaControllerGetWeek.PATH, 'get');
  if (params) {
    rb.query('professionalId', params.professionalId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentResponseDto>>;
    })
  );
}

agendaControllerGetWeek.PATH = '/api/agenda/week';
