/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailableSlotResponseDto } from '../../models/available-slot-response-dto';

export interface AgendaControllerGetAvailable$Params {

/**
 * Fecha para consultar (YYYY-MM-DD)
 */
  date: string;

/**
 * ID del profesional (si es diferente al logueado)
 */
  professionalId?: number;
}

export function agendaControllerGetAvailable(http: HttpClient, rootUrl: string, params: AgendaControllerGetAvailable$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailableSlotResponseDto>> {
  const rb = new RequestBuilder(rootUrl, agendaControllerGetAvailable.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
    rb.query('professionalId', params.professionalId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvailableSlotResponseDto>;
    })
  );
}

agendaControllerGetAvailable.PATH = '/agenda/available';
