/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProfileResponseDto } from '../../models/profile-response-dto';

export interface AuthControllerGetProfile$Params {
}

export function authControllerGetProfile(http: HttpClient, rootUrl: string, params?: AuthControllerGetProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfileResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerGetProfile.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProfileResponseDto>;
    })
  );
}

authControllerGetProfile.PATH = '/auth/profile';
