/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PermissionResponseDto } from '../../models/permission-response-dto';

export interface PermissionsControllerFindAll$Params {
}

export function permissionsControllerFindAll(http: HttpClient, rootUrl: string, params?: PermissionsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PermissionResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, permissionsControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PermissionResponseDto>>;
    })
  );
}

permissionsControllerFindAll.PATH = '/api/permissions';
