/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRewardProgramDto } from '../../models/create-reward-program-dto';
import { RewardProgramResponseDto } from '../../models/reward-program-response-dto';

export interface RewardsControllerCreateRewardProgram$Params {
      body: CreateRewardProgramDto
}

export function rewardsControllerCreateRewardProgram(http: HttpClient, rootUrl: string, params: RewardsControllerCreateRewardProgram$Params, context?: HttpContext): Observable<StrictHttpResponse<RewardProgramResponseDto>> {
  const rb = new RequestBuilder(rootUrl, rewardsControllerCreateRewardProgram.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RewardProgramResponseDto>;
    })
  );
}

rewardsControllerCreateRewardProgram.PATH = '/api/rewards/programs';
