/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailLogsPaginatedResponseDto } from '../../models/email-logs-paginated-response-dto';

export interface EmailControllerGetEmailLogs$Params {
  status?: 'sent' | 'failed' | 'pending' | 'scheduled';
  startDate?: string;
  endDate?: string;
  templateId?: string;
  page?: number;
  limit?: number;
}

export function emailControllerGetEmailLogs(http: HttpClient, rootUrl: string, params?: EmailControllerGetEmailLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailLogsPaginatedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerGetEmailLogs.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('templateId', params.templateId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailLogsPaginatedResponseDto>;
    })
  );
}

emailControllerGetEmailLogs.PATH = '/api/email/logs';
