/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailOperationResultDto } from '../../models/email-operation-result-dto';

export interface EmailControllerCleanQueue$Params {
}

export function emailControllerCleanQueue(http: HttpClient, rootUrl: string, params?: EmailControllerCleanQueue$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailOperationResultDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerCleanQueue.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailOperationResultDto>;
    })
  );
}

emailControllerCleanQueue.PATH = '/email/queue/clean';
