/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailSendResponseDto } from '../../models/email-send-response-dto';

export interface EmailControllerSendWelcomeEmail$Params {
  userId: string;
}

export function emailControllerSendWelcomeEmail(http: HttpClient, rootUrl: string, params: EmailControllerSendWelcomeEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailSendResponseDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerSendWelcomeEmail.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailSendResponseDto>;
    })
  );
}

emailControllerSendWelcomeEmail.PATH = '/api/email/send/welcome/{userId}';
