/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailTemplateResponseDto } from '../../models/email-template-response-dto';
import { UpdateEmailTemplateDto } from '../../models/update-email-template-dto';

export interface EmailControllerUpdateTemplate$Params {
  id: string;
      body: UpdateEmailTemplateDto
}

export function emailControllerUpdateTemplate(http: HttpClient, rootUrl: string, params: EmailControllerUpdateTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailTemplateResponseDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerUpdateTemplate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailTemplateResponseDto>;
    })
  );
}

emailControllerUpdateTemplate.PATH = '/email/templates/{id}';
