/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailSettingsDto } from '../../models/email-settings-dto';
import { TestConnectionResponseDto } from '../../models/test-connection-response-dto';

export interface EmailControllerValidateSmtpSettings$Params {
      body: EmailSettingsDto
}

export function emailControllerValidateSmtpSettings(http: HttpClient, rootUrl: string, params: EmailControllerValidateSmtpSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<TestConnectionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerValidateSmtpSettings.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestConnectionResponseDto>;
    })
  );
}

emailControllerValidateSmtpSettings.PATH = '/email/settings/validate';
