/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailTemplateResponseDto } from '../../models/email-template-response-dto';

export interface EmailControllerGetTemplateById$Params {
  id: string;
}

export function emailControllerGetTemplateById(http: HttpClient, rootUrl: string, params: EmailControllerGetTemplateById$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailTemplateResponseDto>> {
  const rb = new RequestBuilder(rootUrl, emailControllerGetTemplateById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailTemplateResponseDto>;
    })
  );
}

emailControllerGetTemplateById.PATH = '/email/templates/{id}';
