/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationOperationDto } from '../../models/notification-operation-dto';

export interface NotificationControllerSendTestAppointmentConfirmation$Params {
  appointmentId: number;
}

export function notificationControllerSendTestAppointmentConfirmation(http: HttpClient, rootUrl: string, params: NotificationControllerSendTestAppointmentConfirmation$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationOperationDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerSendTestAppointmentConfirmation.PATH, 'post');
  if (params) {
    rb.path('appointmentId', params.appointmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationOperationDto>;
    })
  );
}

notificationControllerSendTestAppointmentConfirmation.PATH = '/api/notifications/send-test-appointment-confirmation/{appointmentId}';
