/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebSocketTestDto } from '../../models/web-socket-test-dto';
import { WebSocketTestResponseDto } from '../../models/web-socket-test-response-dto';

export interface NotificationControllerTestBroadcast$Params {
      body: WebSocketTestDto
}

export function notificationControllerTestBroadcast(http: HttpClient, rootUrl: string, params: NotificationControllerTestBroadcast$Params, context?: HttpContext): Observable<StrictHttpResponse<WebSocketTestResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerTestBroadcast.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebSocketTestResponseDto>;
    })
  );
}

notificationControllerTestBroadcast.PATH = '/api/notifications/test-broadcast';
