/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebSocketStatsDto } from '../../models/web-socket-stats-dto';

export interface NotificationControllerGetWebSocketStats$Params {
}

export function notificationControllerGetWebSocketStats(http: HttpClient, rootUrl: string, params?: NotificationControllerGetWebSocketStats$Params, context?: HttpContext): Observable<StrictHttpResponse<WebSocketStatsDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerGetWebSocketStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebSocketStatsDto>;
    })
  );
}

notificationControllerGetWebSocketStats.PATH = '/api/notifications/websocket-stats';
