/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateNotificationDto } from '../../models/create-notification-dto';
import { NotificationResponseDto } from '../../models/notification-response-dto';

export interface NotificationControllerCreateNotification$Params {
      body: CreateNotificationDto
}

export function notificationControllerCreateNotification(http: HttpClient, rootUrl: string, params: NotificationControllerCreateNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerCreateNotification.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationResponseDto>;
    })
  );
}

notificationControllerCreateNotification.PATH = '/api/notifications';
