/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationSummaryResponseDto } from '../../models/notification-summary-response-dto';

export interface NotificationControllerGetSummary$Params {
}

export function notificationControllerGetSummary(http: HttpClient, rootUrl: string, params?: NotificationControllerGetSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationSummaryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationControllerGetSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationSummaryResponseDto>;
    })
  );
}

notificationControllerGetSummary.PATH = '/notifications/summary';
