/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BusinessTypePublicControllerGetConsultationTemplate$Params {

/**
 * Código del tipo de negocio (veterinary, psychology, beauty, hair_salon, medical)
 */
  code: string;
}

export function businessTypePublicControllerGetConsultationTemplate(http: HttpClient, rootUrl: string, params: BusinessTypePublicControllerGetConsultationTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, businessTypePublicControllerGetConsultationTemplate.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

businessTypePublicControllerGetConsultationTemplate.PATH = '/public/business-types/code/{code}/consultation-template';
