/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductPackagingDto } from '../../models/product-packaging-dto';
import { UpdateProductPackagingDto } from '../../models/update-product-packaging-dto';

export interface InventoryControllerUpdateProductPackaging$Params {

/**
 * ID del producto
 */
  id: number;
      body: UpdateProductPackagingDto
}

export function inventoryControllerUpdateProductPackaging(http: HttpClient, rootUrl: string, params: InventoryControllerUpdateProductPackaging$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductPackagingDto>> {
  const rb = new RequestBuilder(rootUrl, inventoryControllerUpdateProductPackaging.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductPackagingDto>;
    })
  );
}

inventoryControllerUpdateProductPackaging.PATH = '/inventory/products/{id}/packaging';
