/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecentMovementsDto } from '../../models/recent-movements-dto';

export interface InventoryControllerGetRecentMovements$Params {
  limit?: number;
}

export function inventoryControllerGetRecentMovements(http: HttpClient, rootUrl: string, params?: InventoryControllerGetRecentMovements$Params, context?: HttpContext): Observable<StrictHttpResponse<RecentMovementsDto>> {
  const rb = new RequestBuilder(rootUrl, inventoryControllerGetRecentMovements.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RecentMovementsDto>;
    })
  );
}

inventoryControllerGetRecentMovements.PATH = '/inventory/movements/recent';
