/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InventoryDashboardMetricsDto } from '../../models/inventory-dashboard-metrics-dto';

export interface InventoryControllerGetDashboardMetrics$Params {
}

export function inventoryControllerGetDashboardMetrics(http: HttpClient, rootUrl: string, params?: InventoryControllerGetDashboardMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<InventoryDashboardMetricsDto>> {
  const rb = new RequestBuilder(rootUrl, inventoryControllerGetDashboardMetrics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InventoryDashboardMetricsDto>;
    })
  );
}

inventoryControllerGetDashboardMetrics.PATH = '/inventory/dashboard/metrics';
