/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductDimensionsDto } from '../../models/product-dimensions-dto';

export interface InventoryControllerGetProductDimensions$Params {

/**
 * ID del producto
 */
  id: number;
}

export function inventoryControllerGetProductDimensions(http: HttpClient, rootUrl: string, params: InventoryControllerGetProductDimensions$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductDimensionsDto>> {
  const rb = new RequestBuilder(rootUrl, inventoryControllerGetProductDimensions.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductDimensionsDto>;
    })
  );
}

inventoryControllerGetProductDimensions.PATH = '/inventory/products/{id}/dimensions';
