/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InventoryDashboardAdvancedMetricsDto } from '../../models/inventory-dashboard-advanced-metrics-dto';

export interface InventoryControllerGetAdvancedDashboardMetrics$Params {
}

export function inventoryControllerGetAdvancedDashboardMetrics(http: HttpClient, rootUrl: string, params?: InventoryControllerGetAdvancedDashboardMetrics$Params, context?: HttpContext): Observable<StrictHttpResponse<InventoryDashboardAdvancedMetricsDto>> {
  const rb = new RequestBuilder(rootUrl, inventoryControllerGetAdvancedDashboardMetrics.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InventoryDashboardAdvancedMetricsDto>;
    })
  );
}

inventoryControllerGetAdvancedDashboardMetrics.PATH = '/inventory/dashboard/advanced-metrics';
