/**
 * Backoffice Hub API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionResponseDto { 
    id: number;
    name: string;
    description: string;
    durationInMonths: number;
    price: number;
}

